//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootShoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTovar
    {
        public int Id_OrderTovar { get; set; }
        public int Id_Tovar { get; set; }
        public int Id_Order { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
